language: c++

matrix:
  include:

    - os: osx
      osx_image: xcode9.1

    - os: linux
      compiler: clang

    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - cmake
          - g++-5

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
  - ./test_Graph
  - ./test_Network
